---
- name: Get NVM version
  shell: . ~/.nvm/nvm.sh && nvm --version
  register: nvm_version
  changed_when: False
  failed_when: False

- set_fact: nvm_valid={{ nvm_version.rc == 0 }}

- name: NVM CHECKING
  debug: "msg='Current NVM version is: {{nvm_version.stdout}}'"
  when: nvm_valid

- name: NVM CHECKING
  debug: "msg='NVM not installed. The task NVM installer is starting ...'"
  when: not nvm_valid
