---

- name: get stats on nvm
  stat: path=~/.nvm
  register: nvm_stat

- include: nvm.yml
  when: not nvm.stat.exists

- name: get stats on npm
  stat: path=~/.npm
  register: npm_stat

- include: npm.yml
  when: not nvm.stat.exists
