---
- include: get_nvm_status.yml
- block:
  - include: nvm.yml
  - include: get_nvm_status.yml
  when: not nvm_valid

- include: get_npm_status.yml
- block:
  - include: npm.yml
  - include: get_npm_status.yml
  when: not npm_valid
