---
- name: Install oh-my-zsh, powerlevel9k theme, fzf, autosuggestions, syntax-highlighting
  hosts: all
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  environment:
    NVM_DIR: "/home/{{main_user}}/.nvm"
  roles:
    - common
    - zsh
    - nvm
