---
- name: Install Full Rails Server with postgres, nginx, elasticsearch, redis v.v.v.
  hosts: all
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  environment:
    NVM_DIR: "/home/{{main_user}}/.nvm"
  roles:
    - common
    - zsh
    - nvm
    - rvm
    - redis
    - postgresql
