---
- name: Get RVM version
  shell: ~/.rvm/bin/rvm --version
  register: rvm_version
  changed_when: False
  failed_when: False

- set_fact: rvm_valid={{ rvm_version.rc == 0 }}

- name: RVM CHECKING
  debug: "msg='Current RVM version is: {{rvm_version.stdout}}'"
  when: rvm_valid

- name: RVM CHECKING
  debug: "msg='RVM not installed. The task RVM installer is starting ...'"
  when: not rvm_valid
