---
- name: Clone fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: ~/.fzf
    update: no
    depth: 1

- name: install fzf
  shell: ~/.fzf/install

- name: Insert fzf to zshrc
  lineinfile:
    path: ~/.zshrc
    line: '[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh'
    state: present


