---
- name: get stats on oh-my-zsh
  stat: path=~/.oh-my-zsh
  register: oh_my_zsh_stat

- name: get stats on fzf
  stat: path=~/.fzf
  register: fzf_stat

- name: Install zsh
  package:
    name: zsh
    state: present
    update_cache: yes
  become: True

- include: oh-my-zsh.yml
  when: not oh_my_zsh_stat.stat.exists

- include: fzf.yml
  when: not fzf_stat.stat.exists

- name: Set default shell to {{ default_shell }}
  become: True
  user:
    name: "{{ item }}"
    shell: "/bin/{{ default_shell }}"
  with_items:
    - "{{ main_user }}"
    - root
