---
- name: Install common packages
  package:
    name: '{{item}}'
    state: present
    update_cache: yes
  become: True
  with_items:
    - git
    - git-core
    - libjpeg-dev
    - libpq-dev
    - htop
    - curl
    - python-dev
    - python-pip
    - python-psycopg2
    - python-setuptools
